Algoritmo "idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2025
Var
// Seção de Declarações das variáveis 
idade: inteiro




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("idade digite sua idade: ")
leia(idade)


se nao( idade >= 18)

Fimalgoritmo