Algoritmo "parOuimoar"
// Disciplina   : [Lógica de Programação]
// Professor   : Jésse braga
// Descrição   : jogo interrativo usando múmero aleatoorio e logios condionaç
// Autor(a)    : Nome do(a) aluno(Devyd)
// Data atual  : 19/03/2025
Var
// Seção de Declarações das variáveis 
jogada,console: inteiro
palpite: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 console <-

Fimalgoritmo